---

- name: Checking if docker has already been installed
  stat:
    path: /etc/_docker_installed
  register: "_docker_installed"

- name: Download installer
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
  when:
    - not _docker_installed.stat.exists

- name: Install docker
  shell: "sh /tmp/get-docker.sh"
  when:
    - not _docker_installed.stat.exists

- name: Create docker config directory
  file:
    path: /etc/docker
    state: directory
    mode: 0600
    owner: root
    group: root

- name: Allow live reload
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Marking as bootstrapped
  file:
    path: /etc/_docker_installed
    state: "touch"

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes

#
# By this point the 'deploy' user must have been created so we can
# add it to the Docker group. This is a requirement with RKE (docs) but may not
# be strictly necessary since the RKE command runs with sudo anyways
#
- name: Add the 'deploy' user to the 'docker' group
  shell:
    cmd: "usermod -aG docker deploy"